version: '2.3'
services:
  gpu-training:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '8gb'
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - .:/pytorch-distributed-training-k8s
    working_dir: /pytorch-distributed-training-k8s
    command: tail -f /dev/null